### GET ALL ITEMS
GET http://localhost:5000/items HTTP/1.1

### GET ONE ITEMS
GET http://localhost:5000/items/3 HTTP/1.1

### ADD ONE ITEMS
POST http://localhost:5000/additems HTTP/1.1
Content-Type: application/json

{
    "name" : "Stronzo",
    "price": "300"
}

### DELETE ONE ITEMS
DELETE http://localhost:5000/items/1 HTTP/1.1
